# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-05 04:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='state',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
