# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-05 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0003_auto_20180805_1226'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='state',
            table='State',
        ),
    ]
