# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-05 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_one', '0006_auto_20180805_1246'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='state',
            table=None,
        ),
    ]
